include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.drift.dart"
    - "build/**"

linter:
  rules:
    prefer_single_quotes: true
    always_declare_return_types: true
